os: linux
dist: xenial

matrix:
  fast_finish: true

before_script:
  - pyenv install 3.9.7
  - pyenv local 3.9.7
  - pip install pip --upgrade --user
  - pip install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - pip install --user aws-sam-cli

script: pip --version
