arch: amd64
language: shell
os: linux
dist: focal
install: skip

jobs:
  include:
    - script: sleep 120
    - script: sleep 180
    - script: sleep 200
    - script: sleep 500
    - script: sleep 400
    - script: sleep 150
    - script: sleep 450
    - script: sleep 350
