sudo: true
language: php
dist: xenial

# Adjust the version of PHP to match your production environment.
# Making this version number greater than the production environment can have unintended consequences
# including a non-functional prod environment.
php:
  - 7.4

matrix:
  fast_finish: true

services:
  - mysql

jdk:
  - oraclejdk8
