os: linux
group: edge
dist: trusty

language: android

android:
  components:
    - tools
    - build-tools-30.0.3
    - android-30

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 11.0.12-open

script:
  - java -version
