language: ruby
dist: bionic
before_install:
  - gem install bundler
script:
  - rvm --version
  - ruby --version
  - rake --version
matrix:
  fast_finish: true
  include:
    - os: osx
      osx_image: xcode13.3
      rvm: 3.1.2
    - os: osx
      osx_image: xcode13.3
      rvm: 3.0.4
