group: edge
dist: trusty
services:
  - docker
language: java

stages:
  - build-cdp
  - tests
  - artifacts

install: skip

jobs:
  include:
    - stage: build-cdp
      name: "Build CDP-API"
      language: java
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
    - stage: build-cdp
      name: "Build Forked Unomi and Yotpo-Unomi"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 8.0.302-open
        - sdk use java 8.0.302-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
    - stage: build-cdp
      name: "Build Unomi Anonymizer"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
    - stage: build-cdp
      name: "Build CDP Ingestion"
      language: java
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 8.0.302-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
      after_script:
        - echo $JAVA_HOME
    - stage: build-cdp
      name: "Build CDP Metorikku docker"
      jdk: openjdk8
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 8.0.302-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2

    - stage: build-cdp
      name: "Build common"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
      after_script:
        - echo $JAVA_HOME

    - stage: tests
      name: "System Tests - Component Test"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
    - stage: tests
      name: "System Tests - Unomi Rules"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
      after_script:
        - echo $JAVA_HOME
    - stage: tests
      name: "System Tests - Unomi Api"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
    - stage: tests
      name: "System Tests - Unomi Conditions"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
      after_script:
        - echo $JAVA_HOME
    - stage: tests
      name: "Build cdp-sdk"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
#    - stage: tests
#      name: "Integration Tests"
#      language: java
#      install:
#        - sudo apt-get install awscli
#        - ./scripts/setup_docker_credentials.sh
#      script:
#        - ./scripts/run_integration_test.sh
    - stage: artifacts
      name: "Publish cdp avro-schemas to JFrog"
      script:
        - sleep 1
    - stage: artifacts
      name: "Publish cdp common to JFrog"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
      after_script:
        - echo $JAVA_HOME
    - stage: artifacts
      name: "Publish cdp sdk to JFrog"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
    - stage: artifacts
      name: "Publish common avro to JFrog"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 1
      after_script:
        - echo $JAVA_HOME
    - stage: artifacts
      name: "Deploy forked Unomi"
      before_install:
        - curl -s "https://get.sdkman.io" | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - sdk install java 11.0.12-open
        - java -version
      script:
        - echo $JAVA_HOME
        - sleep 2
      after_script:
        - echo $JAVA_HOME
      if: branch = master
