language: node_js

node_js:
  - node

python:
  - "3.7"

cache:
  - pip

install:
  - pip install --user awscli
  - npm install

before_script:
  - npm install grunt-cli -g
  - gem install sass

script:
  - node --version
