language: ruby
dist: bionic
branches:
  only:
    - master
before_install:
  - gem install bundler
script:
  - rvm  --version
matrix:
  fast_finish: true
  include:
    - os: linux
      rvm: 3.1.2
    - os: osx
      osx_image: xcode13.3
      rvm: 3.1.2
    - os: linux
      rvm: 3.0.4
    - os: osx
      osx_image: xcode13.3
      rvm: 3.0.4
    - os: linux
      rvm: 2.7.6
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.6
    - os: linux
      rvm: 2.6.10
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.10
    - os: linux
      rvm: 2.5.8
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.8
    - os: linux
      rvm: 2.4.10
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.10
    - os: linux
      rvm: 2.3.8
    - os: linux
      rvm: 3.1.1
    - os: osx
      osx_image: xcode13.3
      rvm: 3.1.1
    - os: linux
      rvm: 3.0.3
    - os: osx
      osx_image: xcode13.3
      rvm: 3.0.3
    - os: linux
      rvm: 2.7.5
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.5
    - os: linux
      rvm: 2.6.9
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.9
    - os: linux
      rvm: 2.5.7
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.7
    - os: linux
      rvm: 2.4.9
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.9
    - os: linux
      rvm: 2.3.7
    - os: linux
      rvm: 3.1.0
    - os: osx
      osx_image: xcode13.3
      rvm: 3.1.0
    - os: linux
      rvm: 3.0.2
    - os: osx
      osx_image: xcode13.3
      rvm: 3.0.2
    - os: linux
      rvm: 2.7.4
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.4
    - os: linux
      rvm: 2.6.8
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.8
    - os: linux
      rvm: 2.5.6
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.6
    - os: linux
      rvm: 2.4.8
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.8
    - os: linux
      rvm: 2.3.6
    - os: linux
      rvm: 3.0.1
    - os: osx
      osx_image: xcode13.3
      rvm: 3.0.1
    - os: linux
      rvm: 2.7.3
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.3
    - os: linux
      rvm: 2.6.7
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.7
    - os: linux
      rvm: 2.5.5
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.5
    - os: linux
      rvm: 2.4.7
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.7
    - os: linux
      rvm: 2.3.5
    - os: linux
      rvm: 3.0.0
    - os: osx
      osx_image: xcode13.3
      rvm: 3.0.0
    - os: linux
      rvm: 2.7.2
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.2
    - os: linux
      rvm: 2.6.6
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.6
    - os: linux
      rvm: 2.5.4
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.4
    - os: linux
      rvm: 2.4.6
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.6
    - os: linux
      rvm: 2.3.4
    - os: linux
      rvm: 2.7.1
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.1
    - os: linux
      rvm: 2.6.5
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.5
    - os: linux
      rvm: 2.5.3
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.3
    - os: linux
      rvm: 2.4.5
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.5
    - os: linux
      rvm: 2.3.3
    - os: linux
      rvm: 2.7.0
    - os: osx
      osx_image: xcode13.3
      rvm: 2.7.0
    - os: linux
      rvm: 2.6.4
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.4
    - os: linux
      rvm: 2.5.2
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.2
    - os: linux
      rvm: 2.4.4
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.4
    - os: linux
      rvm: 2.3.2
    - os: linux
      rvm: 2.6.3
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.3
    - os: linux
      rvm: 2.5.1
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.1
    - os: linux
      rvm: 2.4.3
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.3
    - os: linux
      rvm: 2.3.1
    - os: linux
      rvm: 2.6.2
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.2
    - os: linux
      rvm: 2.5.0
    - os: osx
      osx_image: xcode13.3
      rvm: 2.5.0
    - os: linux
      rvm: 2.4.2
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.2
    - os: linux
      rvm: 2.3.0
    - os: linux
      rvm: 2.6.1
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.1
    - os: linux
      rvm: 2.4.1
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.1
    - os: linux
      rvm: 2.6.0
    - os: osx
      osx_image: xcode13.3
      rvm: 2.6.0
    - os: linux
      rvm: 2.4.0
    - os: osx
      osx_image: xcode13.3
      rvm: 2.4.0
